### ISSUE TITLE
The Installation Question: 

### ISSUE THREAD

**Issue by ghost** [Heropowerbrine/another-testing#2]
## What is your question?
![Screenshot_20220813-231451](https://user-images.githubusercontent.com/109828559/184510918-c444433d-7fc3-472c-894f-ba1d019bdc6f.png)
I Have Account, But I Can't Install.

**Comment by Heropowerbrine** [comment]
https://github.com/Heropowerbrine/Friday-Night-Funkin-The-Shaggyverse-Android/releases/tag/Android
Download from this release, I don't require people to install from actions unless it's a test build

**Comment by ghost** [comment]
Oh, Okay, Thank You So Much
